### ISSUE TITLE
prevent text selection in FF

### ISSUE THREAD

**Issue by davetayls** [davetayls/jquery.kinetic#30]
Currently FF will create a text selection as you drag.

example: http://jsbin.com/afegim/1/

**Comment by skeksify** [comment]
My little tweak for the issue:
```js
$('.scrollable-wrapper').kinetic({
    'moved': function(){ $('body').addClass('inselectable'); },
    'stopped': function(){ $('body').removeClass('inselectable'); }
});
// Sometimes stopped doesn't get called last
$('body').mouseup(function(){$('body').removeClass('inselectable');}); 
```

When
```css
.inselectable {
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}
```
